### ISSUE TITLE
FlutterPubVersionChecker is incompatible with IntelliJ 2019.3, current version.

### ISSUE THREAD

**Issue by mhadaily** [pszklarska/FlutterPubVersionChecker#12]
Hi, 
It seems there should be an update in the plugin to make it compatible with the current version of IntelliJ. 

you have a look and let me know if I can help with that. 

thanks,

**Comment by pszklarska** [comment]
Hi @mhadaily! Thanks for your comment. I upgraded plugin to be compatible with the newest IntelliJ version, it should be visible to install within two days 👍

**Comment by mhadaily** [comment]
Thanks, It seems your plugin cannot be found on Intellij Marketplace anymore. not sure why, at least I am not able to find it anymore. I wanted to just let you know.

**Comment by pszklarska** [comment]
Hi @mhadaily! Thanks for letting me know, it should be fixed now and plugin is visible again in the marketplace 👍
