### ISSUE TITLE
Not working with Android Studio 3.6.1

### ISSUE THREAD

**Issue by radvansky-tomas** [pszklarska/FlutterPubVersionChecker#15]
Plugin is visible in market place, updated...however not working

Android Studio 3.6.1
Build #AI-192.7142.36.36.6241897, built on February 27, 2020
Runtime version: 1.8.0_212-release-1586-b4-5784211 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.3
GC: ParNew, ConcurrentMarkSweep
Memory: 1237M
Cores: 16
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: net.seesharpsoft.intellij.plugins.csv, Dart, io.flutter, de.mariushoefler.flutter_enhancement_suite, pl.pszklarska.pubversionchecker

**Comment by pszklarska** [comment]
Hi @radvansky-tomas! Thanks for this report. 
Can you provide more details? By "not working" do you mean that you don't see warnings in pubspec.yaml, or is "Update dependency" fix not working?

**Comment by radvansky-tomas** [comment]
Thank you for quick reply.
By not working I mean that in Android studio I dont see yellow highlighted plugins with possible update version like before.

Ie. plugin is installed and its enabled. But nothing is happening.

**Comment by radvansky-tomas** [comment]
I dont know if something changed, but it works again

**Comment by pszklarska** [comment]
Good to hear that 👍 I'm closing this issue then
