### ISSUE TITLE
Not Compatible with Intellij 2020.1 Ultimate

### ISSUE THREAD

**Issue by softronaut** [pszklarska/FlutterPubVersionChecker#16]
After latest update, I won't able to use the plugin.

<img width="336" alt="Screen Shot 2020-04-11 at 12 26 47 PM" src="https://user-images.githubusercontent.com/43244505/79040222-ba3a3b00-7bef-11ea-8fde-dbfc37fe7f4d.png">

```
IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.121, built on April 8, 2020
Runtime version: 11.0.6+8-b765.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
```

Thanks for your work!

**Comment by pszklarska** [comment]
@softronaut thanks for filing an issue! I updated the plugin, new version (1.2.2) with the support for IntelliJ 2020.x.x should be available within 2 days 👍
