### ISSUE TITLE
Android studio white cursor not letting me to type

### ISSUE THREAD

**Issue by planets-9** [pszklarska/FlutterPubVersionChecker#18]
I have gone through [this post](https://stackoverflow.com/questions/28606348/close-white-cursor-in-android-studio) and tried all the solutions but none of them worked. 

Screenshot:

[![enter image description here][1]][1]

It started after I installed [Flutter Pub Version Checker](https://plugins.jetbrains.com/plugin/12400-flutter-pub-version-checker) plugin, and I remember Android Studio popped up a dialog asking something like, (I don't remember all the details)

>Do you want to allow multiple entries on holding a button X, you can always run xyz command to get back...

I agreed to that block and then I started having this issue. Here is the [Stackoverflow question link](https://stackoverflow.com/questions/61742317/android-studio-white-cursor-not-letting-me-to-type):

  [1]: https://i.stack.imgur.com/dWx1g.gif

**Comment by pszklarska** [comment]
Hey @planets-9, it looks more like an issue with Android Studio (probably changing settings would work), not a plugin itself, so I'm closing this.
