### ISSUE TITLE
PyCharm support

### ISSUE THREAD

**Issue by cosmincatalin** [pszklarska/FlutterPubVersionChecker#2]
PyCharm can benefit from this plugin as well. especially for projects that are Dart based but not Flutter based.

**Comment by pszklarska** [comment]
Thanks for the idea! I'll check if it's possible :)

**Comment by pszklarska** [comment]
After a short research, I found out that it's not so easy, because of differences in plugins API system between Java and Python (according to [this SO answer](https://stackoverflow.com/a/53173295/3213173)). So I'll not handle this for now 😟 But PRs are welcome!
