### ISSUE TITLE
Checks and highlights incorrect field when using a custom pub server

### ISSUE THREAD

**Issue by MisterJimson** [pszklarska/FlutterPubVersionChecker#20]
![Screen Shot 2020-06-17 at 11 26 20 AM](https://user-images.githubusercontent.com/7351329/84917487-67687e00-b08d-11ea-9274-592fecfecc1b.png)

**Comment by pszklarska** [comment]
Hi @MisterJimson! Thanks for your feedback, I'll make an improvement for this issue in the next release 👍

**Comment by pszklarska** [comment]
Hey! This issue is fixed in 1.2.3, within 2 days should be available for the download.
