### ISSUE TITLE
An issue with dependencies that have the same suffix.

### ISSUE THREAD

**Issue by serhii-k** [pszklarska/FlutterPubVersionChecker#21]
Hello Paulina,

There is a minor issue with plugins that have the same suffix.

The following image contains an example with:
- path_provider (version 1.6.11),
- and provider (version 4.3.1).

<img width="538" alt="Screenshot 2020-07-28 at 17 42 36" src="https://user-images.githubusercontent.com/10563821/88681936-c42e6e00-d0fa-11ea-876f-9869ecd752cc.png">

**Comment by pszklarska** [comment]
Thanks for reporting! I'll look into that 👍

**Comment by pszklarska** [comment]
Hey @serhii-k, this issue should be fixed in the newest version of the plugin (1.2.5), which will be available within the next 2 days. 
Once again, thanks for reporting the issue!

**Comment by serhii-k** [comment]
@pszklarska Thank you very much, Paulina! 😃
