### ISSUE TITLE
[Feature]All update

### ISSUE THREAD

**Issue by shinriyo** [pszklarska/FlutterPubVersionChecker#23]
I want all update feature.
selecting by module is trouble some

**Comment by pszklarska** [comment]
Hey @shinriyo! I added that functionality in the newest release (1.3.0) :) 
It should be ready to download from the Market in the next 1-2 days

<img width="1468" alt="flutter-pub-version-checker-2" src="https://user-images.githubusercontent.com/8558760/139529105-b21610e8-27d2-46e0-9de2-d1e0dd9ae719.png">

**Comment by shinriyo** [comment]
😎 cool!thank you
