### ISSUE TITLE
[Feature]github jumping

### ISSUE THREAD

**Issue by shinriyo** [pszklarska/FlutterPubVersionChecker#24]
I want github page of plugin URL jumping future!

**Comment by pszklarska** [comment]
Hey! Thanks for that request. I also think it would be super handy, but unfortunately, IntelliJ plugin API doesn't allow it. See my comment here for more info: https://github.com/pszklarska/FlutterPubVersionChecker/issues/6#issuecomment-518139050

I'm closing it, for now. Hopefully reopening in the future when it'll be possible 🤞
