### ISSUE TITLE
wrong latest version alert for prerelease plugins(null safety)

### ISSUE THREAD

**Issue by bhanuka96** [pszklarska/FlutterPubVersionChecker#38]
[plugin](https://pub.dev/packages/excel)

latest prerelease version is `2.0.0-null-safety-3`. but show alert to upgrade. after click update dependecy button it's update to the `1.1.5`

<img width="676" alt="Screenshot 2021-10-25 at 10 21 23 PM" src="https://user-images.githubusercontent.com/34953062/138737707-273bdd2f-8d42-45da-a70b-be1daf1e23fa.png">
l)

**Comment by boskokg** [comment]
Hello @pszklarska 
Thank you for your plugin! It is one of the must have it !!!

Is there a chance to make a support for this issue?

Thanks in advance

**Comment by pszklarska** [comment]
Hey @bhanuka96 and @boskokg! That feature is added in this PR #59 and will be available soon in the plugin :) 

Once a new version (1.3.5) of a plugin is available, you'll see an option in IDE settings to include preview and prerelease versions of the packages.

**Comment by boskokg** [comment]
@pszklarska thank you!
