### ISSUE TITLE
Add quick fix to show changelog

### ISSUE THREAD

**Issue by cbenhagen** [pszklarska/FlutterPubVersionChecker#4]
Often we would need to quickly check the changelog for breaking changes etc

**Comment by pszklarska** [comment]
Unfortunately in the current version of the Pub API it's not possible to get a changelog.

**Comment by cbenhagen** [comment]
Can you create an feature request issue for this?

**Comment by pszklarska** [comment]
I creates such an issue (https://github.com/dart-lang/pub-dev/issues/2339), but for now it's not that easy to implement this. I'm closing this issue for now

**Comment by ThinkDigitalSoftware** [comment]
You can get it from scraping if you want based on the url. The API should provide the url to at least access the files needed to grab this information
