### ISSUE TITLE
[feature] Go do pub.dev

### ISSUE THREAD

**Issue by danielgomezrico** [pszklarska/FlutterPubVersionChecker#54]
Hi

I would be nice to let you go to pub.dev for the library to see changelog and/or Version History from the actions box in the browser:
![image](https://user-images.githubusercontent.com/76348/151577848-39a5b43b-17e2-490f-b353-d65801880d1a.png)

The links it should open are:
- `https://pub.dev/packages/<library_name>/changelog`
- `https://pub.dev/packages/<library_name>/versions`

**Comment by pszklarska** [comment]
Hey @danielgomezrico, thank you for suggesting that! The last time I checked it wasn't possible due to limitations in the IntelliJ plugin's SDK, but possibly it has changed since then. I'm adding it to my TODO list.

**Comment by pszklarska** [comment]
Hey @danielgomezrico this feature is implemented in #60 and will be available soon in the updated plugin (v1.3.5) :)

**Comment by danielgomezrico** [comment]
Wow! thanks!
