### ISSUE TITLE
Open pub web page

### ISSUE THREAD

**Issue by Nico04** [pszklarska/FlutterPubVersionChecker#6]
It would be very nice if we could open the package pub web site page from the pubspec.yaml 👍

**Comment by pszklarska** [comment]
To be honest I doubt if it's possible in the current version of IntelliJ plugin API.

**Comment by Nico04** [comment]
Then at least show / copy the url?

**Comment by pszklarska** [comment]
I've tried several ways of doing this, but unfortunately none of them is really practical 🙁 Url is too long to be shown in dialog (and it's not possible to copy it from there), and copying programmatically is not possible. 
I'm closing this issue for now.
